import { ReactNode } from "react"
import Navbar from "../components/Navbar";
import Providers from "../components/Provider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface IProps {
  children: ReactNode;
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
